[project]
name = "renovate-uv-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "simplejson==3.19.1",
    "uv==0.6.4",
]
